import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // All generated, not source. public/sw.js and its worker chunks are
    // Serwist build output — linting the bundled worker reports on
    // minified code. next-env.d.ts is regenerated by `next build`/`dev`,
    // and since 15.5 it emits a triple-slash reference to
    // .next/types/routes.d.ts that trips @typescript-eslint's
    // triple-slash-reference rule; the file carries its own "should not
    // be edited" notice, so the only fix available is to skip it.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'public/sw.js',
      'public/swe-worker-*.js',
    ],
  },
];

export default config;
