import { NextResponse, type NextRequest } from 'next/server';
import { adminAccess } from '@/lib/admin/access';
import { formatTimestamp } from '@/lib/admin/format';
import { createClient } from '@/lib/supabase/server';
import { csvRow, ZipBuilder, MAX_ENTRIES } from '@/lib/reports/zip';

/**
 * The College's own copy of every generated report, as one ZIP.
 *
 * This is a *download*, not the backup system. A nightly encrypted `pg_dump`
 * to off-site storage is still unbuilt (ROADMAP.md Phase 3), and this does not
 * replace it: it covers the documents, not the database, and it only exists
 * when somebody presses the button. What it does buy, today, is that the
 * College is not one Supabase incident away from having no copy at all of the
 * assessment reports it has already issued — and it is theirs, on their own
 * disk, in a format they can open without this application.
 *
 * Streamed rather than assembled: at full cohort this is roughly 1 100 PDFs,
 * and buffering them all would exhaust the function's memory long before the
 * download finished. Each file is fetched, emitted, and dropped.
 */
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

type Scope = 'today' | 'week' | 'all';

interface ReportRow {
  id: string;
  trainee_id: string;
  storage_path: string;
  sha256_hash: string;
  generated_by_id: string;
  generated_at: string;
}

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Not signed in.' }, { status: 401 });

  const { data: profile } = await supabase
    .from('users')
    .select('role, active')
    .eq('id', user.id)
    .maybeSingle();

  // Read access is enough: this hands back documents the person can already
  // open one at a time, and the Coordinator's whole role is oversight.
  if (!profile || adminAccess(profile) === 'deny') {
    return NextResponse.json({ error: 'Not permitted.' }, { status: 403 });
  }

  const scope = readScope(request.nextUrl.searchParams.get('scope'));
  const since = scopeStart(scope);

  let query = supabase
    .from('reports')
    .select('id, trainee_id, storage_path, sha256_hash, generated_by_id, generated_at')
    .order('generated_at', { ascending: true })
    .limit(MAX_ENTRIES);
  if (since) query = query.gte('generated_at', since.toISOString());

  const [{ data: reportRows, error }, traineesRes, routesRes, usersRes] = await Promise.all([
    query,
    supabase.from('trainees').select('id, name, registration_number, track, route_id'),
    supabase.from('routes').select('id, code'),
    supabase.from('users').select('id, name'),
  ]);

  if (error) {
    return NextResponse.json(
      { error: `Could not list the reports: ${error.message}` },
      { status: 500 },
    );
  }

  const reports = (reportRows ?? []) as ReportRow[];
  const traineeById = new Map((traineesRes.data ?? []).map((t) => [t.id as string, t]));
  const routeCodeById = new Map(
    (routesRes.data ?? []).map((r) => [r.id as string, r.code as string]),
  );
  const userNameById = new Map(
    (usersRes.data ?? []).map((u) => [u.id as string, u.name as string]),
  );

  const stamp = fileStamp(new Date());
  const zip = new ZipBuilder();
  const encoder = new TextEncoder();

  const stream = new ReadableStream<Uint8Array>({
    async pull(controller) {
      // The manifest and the note go in first, so a partial download — a
      // dropped connection halfway through 400 files — still opens and still
      // explains itself.
      const manifest: string[] = [
        csvRow([
          'File in this archive',
          'Trainee',
          'Registration number',
          'Track',
          'Route',
          'Generated (East Africa Time)',
          'Generated by',
          'SHA-256 of the PDF',
        ]),
      ];

      const entries: { name: string; report: ReportRow }[] = [];
      const usedNames = new Set<string>();

      for (const report of reports) {
        const trainee = traineeById.get(report.trainee_id);
        const routeCode = trainee
          ? (routeCodeById.get(trainee.route_id as string) ?? 'NO-ROUTE')
          : 'NO-ROUTE';
        const base = report.storage_path.split('/').pop() ?? `${report.id}.pdf`;

        // Two reports can share a filename only if the same assessor generated
        // the same trainee's report twice in a day; the id suffix keeps both,
        // because a backup that silently drops one is worse than an ugly name.
        let name = `reports/${routeCode}/${base}`;
        if (usedNames.has(name)) name = `reports/${routeCode}/${report.id.slice(0, 8)}-${base}`;
        usedNames.add(name);

        entries.push({ name, report });
        manifest.push(
          csvRow([
            name,
            trainee?.name ?? '(trainee no longer in the register)',
            trainee?.registration_number ?? '',
            trainee?.track ?? '',
            routeCode,
            formatTimestamp(report.generated_at),
            userNameById.get(report.generated_by_id) ?? '',
            report.sha256_hash,
          ]),
        );
      }

      controller.enqueue(zip.entry('manifest.csv', encoder.encode(manifest.join('')), new Date()));
      controller.enqueue(
        zip.entry('README.txt', encoder.encode(readme(scope, reports.length, stamp)), new Date()),
      );

      let failed = 0;
      const failures: string[] = [];

      for (const { name, report } of entries) {
        const { data, error: downloadError } = await supabase.storage
          .from('reports')
          .download(report.storage_path);

        if (downloadError || !data) {
          // One unreadable file must not abandon the other four hundred. It is
          // named in the archive instead, so the gap is visible rather than
          // silent.
          failed += 1;
          failures.push(`${name} — ${downloadError?.message ?? 'not found in storage'}`);
          continue;
        }

        const bytes = new Uint8Array(await data.arrayBuffer());
        controller.enqueue(zip.entry(name, bytes, new Date(report.generated_at)));
      }

      if (failed > 0) {
        controller.enqueue(
          zip.entry(
            'MISSING-FILES.txt',
            encoder.encode(
              `${failed} report${failed === 1 ? '' : 's'} listed in the register could not be read from storage:\n\n${failures.join('\n')}\n`,
            ),
            new Date(),
          ),
        );
      }

      controller.enqueue(zip.end());
      controller.close();
    },
  });

  return new NextResponse(stream, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="tathmini-reports-${scope}-${stamp}.zip"`,
      // The archive is built as it is sent, so its length is not known up front.
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

function readScope(raw: string | null): Scope {
  return raw === 'today' || raw === 'week' || raw === 'all' ? raw : 'today';
}

/** Start of the window, in East African wall-clock terms rather than UTC. */
function scopeStart(scope: Scope): Date | null {
  if (scope === 'all') return null;
  const now = new Date();
  const eatMidnight = new Date(now.getTime() + 3 * 60 * 60 * 1000);
  eatMidnight.setUTCHours(0, 0, 0, 0);
  const startUtc = new Date(eatMidnight.getTime() - 3 * 60 * 60 * 1000);
  if (scope === 'today') return startUtc;
  return new Date(startUtc.getTime() - 6 * 24 * 60 * 60 * 1000);
}

function fileStamp(date: Date): string {
  const eat = new Date(date.getTime() + 3 * 60 * 60 * 1000);
  return eat.toISOString().slice(0, 10);
}

function readme(scope: Scope, count: number, stamp: string): string {
  const window = {
    today: 'reports generated today',
    week: 'reports generated in the last seven days',
    all: 'every report ever generated',
  }[scope];

  return [
    'TATHMINI — REPORT BACKUP',
    'Morogoro Vocational Teachers Training College',
    '',
    `Made: ${stamp} (East Africa Time)`,
    `Contents: ${window} — ${count} file${count === 1 ? '' : 's'}`,
    '',
    'WHAT THIS IS',
    'A copy of the assessment reports this system has generated, as PDFs, filed',
    'by route. manifest.csv lists every file with the trainee it belongs to and',
    'the SHA-256 hash recorded when it was generated — the same hash held in the',
    'database, so a file can be checked against the record years later.',
    '',
    'WHAT THIS IS NOT',
    'This is not a backup of the database. Marks, results and the audit trail are',
    'NOT in this archive — only the finished report documents. Keep it somewhere',
    'other than the computer that downloaded it.',
    '',
    'CHECKING A FILE',
    'On Windows:  certutil -hashfile "<file>" SHA256',
    'On Mac/Linux: shasum -a 256 "<file>"',
    'Compare the result with the hash in manifest.csv for that file.',
    '',
  ].join('\n');
}
